apiVersion: batch/v1
kind: Job
metadata:
  name: init-osm-db
spec:
  template:
    spec:
      activeDeadlineSeconds: 3600
      initContainers:
      - name: ls
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["ls", "-l", "/var/lib/postgresql/12/main/.."]
        volumeMounts:
        - name: postgres-data
          mountPath: "/var/lib/postgresql/12/main"
      - name: chown-dir
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["chown", "-R", "102:105", "/var/lib/postgresql/12/main"]
        volumeMounts:
        - name: postgres-data
          mountPath: "/var/lib/postgresql/12/main"
      - name: ls2
        image: overv/openstreetmap-tile-server:dups
        imagePullPolicy: IfNotPresent
        command: ["ls", "-l", "/var/lib/postgresql/12/main/.."]
        volumeMounts:
        - name: postgres-data
          mountPath: "/var/lib/postgresql/12/main"
      - name: downloader-data
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["wget", "-O", "/tmp/download/data.osm.pbf", "docker-for-desktop:7890/isle-of-man-latest.osm.pbf"]
        volumeMounts:
        - name: tempdownload
          mountPath: "/tmp/download"
      - name: downloader-poly
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["wget", "-O", "/tmp/download/data.poly", "docker-for-desktop:7890/isle-of-man.poly"]
        volumeMounts:
        - name: tempdownload
          mountPath: "/tmp/download"
      containers:
      - name: osm-data-importer
        image: overv/openstreetmap-tile-server:dups
        imagePullPolicy: IfNotPresent
        args: ["import", "/tmp/download"]
        volumeMounts:
        - name: tempdownload
          mountPath: "/tmp/download"
#TODO : import will try to use /data.osm.pbf and /data.poly files ==> how to remount files into / (not as a volume...) ==> tweak in run.sh : use second argument
        - name: postgres-data
          mountPath: "/var/lib/postgresql/12/main"
      restartPolicy: Never
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: osm-postgres
      - name: tempdownload
        emptyDir: {}
  backoffLimit: 4
